{% set name = "nbterm" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2a2fe28dfaf979d4366dc5c669cd95abedb2494f016bbbc4e525af46c8eefdb1

build:
  noarch: python
  number: 0
  entry_points:
    - nbterm = nbterm.nbterm:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - prompt-toolkit >=3.0.16
    - typer
    - pygments
    - rich
    - kernel_driver

test:
  commands:
    - nbterm --help

about:
  home: https://github.com/davidbrochart/nbterm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tool for viewing, editing and executing Jupyter Notebooks in the terminal
  dev_url: https://github.com/davidbrochart/nbterm

extra:
  recipe-maintainers:
    - davidbrochart
