{% set name = "nbterm" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b94511bb851e10ae0552c09cf7eed3537bcf87cf9b4260ad9bc311882a981607

build:
  noarch: python
  number: 0
  entry_points:
    - nbterm = nbterm.nbterm:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - prompt-toolkit >=3.0.16
    - typer
    - click <8
    - pygments
    - rich
    - kernel_driver >=0.0.6

test:
  commands:
    - nbterm --help

about:
  home: https://github.com/davidbrochart/nbterm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tool for viewing, editing and executing Jupyter Notebooks in the terminal
  dev_url: https://github.com/davidbrochart/nbterm

extra:
  recipe-maintainers:
    - davidbrochart
