{% set name = "nbterm" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 99b080c86b6a5121dc4f7333c4bbd89fc5fedc4af8372892ea6d8e396303cf2d

build:
  noarch: python
  number: 0
  entry_points:
    - nbterm = nbterm.nbterm:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - prompt-toolkit >=3.0.16
    - typer >=0.4.0
    - pygments
    - rich
    - kernel_driver >=0.0.6

test:
  commands:
    - nbterm --help

about:
  home: https://github.com/davidbrochart/nbterm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tool for viewing, editing and executing Jupyter Notebooks in the terminal
  dev_url: https://github.com/davidbrochart/nbterm

extra:
  recipe-maintainers:
    - davidbrochart
